spring:
  profiles:
    active: dev
  flyway:
    locations: classpath:/db/migration

mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.jmtbg.dailyreport.model  # 注意：对应实体类的路径


